
package stubs.cart;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CartWebServiceImplService", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/tcf/cart", wsdlLocation = "file:/Users/mosser/work/polytech/4A_ISA_TheCookieFactory/client/src/main/resources/CartWS.wsdl")
public class CartWebServiceImplService
    extends Service
{

    private final static URL CARTWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CARTWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName CARTWEBSERVICEIMPLSERVICE_QNAME = new QName("http://www.polytech.unice.fr/si/4a/isa/tcf/cart", "CartWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/mosser/work/polytech/4A_ISA_TheCookieFactory/client/src/main/resources/CartWS.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CARTWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        CARTWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public CartWebServiceImplService() {
        super(__getWsdlLocation(), CARTWEBSERVICEIMPLSERVICE_QNAME);
    }

    public CartWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CARTWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public CartWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, CARTWEBSERVICEIMPLSERVICE_QNAME);
    }

    public CartWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CARTWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public CartWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CartWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CartWebService
     */
    @WebEndpoint(name = "CartWebServiceImplPort")
    public CartWebService getCartWebServiceImplPort() {
        return super.getPort(new QName("http://www.polytech.unice.fr/si/4a/isa/tcf/cart", "CartWebServiceImplPort"), CartWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CartWebService
     */
    @WebEndpoint(name = "CartWebServiceImplPort")
    public CartWebService getCartWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.polytech.unice.fr/si/4a/isa/tcf/cart", "CartWebServiceImplPort"), CartWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CARTWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw CARTWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return CARTWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
