
package stubs.customerCare;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomerCareService", targetNamespace = "http://webservice.tcf.isa.polytech.unice.fr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CustomerCareService {


    /**
     * 
     * @param creditCardNumber
     * @param customerName
     * @throws AlreadyExistingCustomerException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "register", targetNamespace = "http://webservice.tcf.isa.polytech.unice.fr/", className = "stubs.customerCare.Register")
    @ResponseWrapper(localName = "registerResponse", targetNamespace = "http://webservice.tcf.isa.polytech.unice.fr/", className = "stubs.customerCare.RegisterResponse")
    public void register(
        @WebParam(name = "customer_name", targetNamespace = "")
        String customerName,
        @WebParam(name = "credit_card_number", targetNamespace = "")
        String creditCardNumber)
        throws AlreadyExistingCustomerException_Exception
    ;

}
